name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.10.0
    with:
      templateVersion: 0.10.0
      rg: az-k8s-ldplay-rg
      resourceName: az-k8s-ldplay
      templateParams: resourceName=az-k8s-ldplay agentCount=1 upgradeChannel=stable JustUseSystemPool=true agentCountMax=20 osDiskType=Managed osDiskSizeGB=32 custom_vnet=true enable_aad=true AksDisableLocalAccounts=true enableAzureRBAC=true adminPrincipalId=_USER_OBJECT_ID_ registries_sku=Premium acrPushRolePrincipalId=_USER_OBJECT_ID_ omsagent=true retentionInDays=30 networkPolicy=azure azurepolicy=audit authorizedIPRanges=["84.53.83.115/32"] ingressApplicationGateway=true appGWcount=0 appGWsku=WAF_v2 appGWmaxCount=10 appgwKVIntegration=true keyVaultAksCSI=true keyVaultCreate=true keyVaultOfficerRolePrincipalId=_USER_OBJECT_ID_ automationAccountScheduledStartStop=Weekday
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
