name: Deploy AKS
run-name: ${{ github.actor }} AKS Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set active account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create AKS cluster
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: az aks create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }} --node-count 1 --enable-addons monitoring --generate-ssh-keys
