name: Deploy AKS
run-name: ${{ github.actor }} AKS Deployment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set active account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create AKS DNS
        uses: azure/aks-dns@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
          dns-name: ${{ secrets.AZURE_AKS_DNS_NAME }}
          location: ${{ secrets.AZURE_LOCATION }}
      # - name: Create AKS cluster
      #   uses: azure/aks-create@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     cluster-name: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
      #     dns-name: ${{ secrets.AZURE_AKS_DNS_NAME }}
      #     location: ${{ secrets.AZURE_LOCATION }}
      #     agent-count: ${{ secrets.AZURE_AKS_AGENT_COUNT }}
      #     agent-vm-size: ${{ secrets.AZURE_AKS_AGENT_VM_SIZE }}
      #     service-principal: ${{ secrets.AZURE_AKS_SERVICE_PRINCIPAL }}
      #     client-secret: ${{ secrets.AZURE_AKS_CLIENT_SECRET }}
      # ssh-publickey: ${{ secrets.AZURE_AKS_SSH_PUBLICKEY }}
      # - name: Deploy to AKS
      #   uses: azure/aks-set-context@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     cluster-name: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
      # - name: Install Otomi on AKS
      #   uses: azure/aks-helm@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     cluster-name: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
      #     chart-name: otomi
      #     chart-version: ${{ secrets.OTOMI_CHART_VERSION }}
