name: Deploy AKS
run-name: ${{ github.actor }} AKS Deployment

on: [push]

env:
  modulePath: ResourceModules/modules/container-service/managed-clusters/main.bicep
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: View file
        # view checked out files
        run: ls -al ./AzureCloud/AzureResourceModules/modules/container-service/managed-clusters/main.bicep
      # - name: Create AKS Cluster
      #   uses: azure/CLI@v1
      #   env:
      #     AKS_CLUSTER_NAME: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
      #   with:
      #     azcliversion: 2.29.0
      #     inlineScript: |
      #       az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      #       az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #       az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ secrets.AZURE_LOCATION }}

      #       az deployment group create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
      #       --template-file ../AzureCloud/AzureResourceModules/modules/container-service/managed-clusters/main.bicep \
      #       --parameter ../AzureCloud/Modules/AzureKubernetesService/Config/aks-default.dev.bicepparam
      # - name: Set context to AKS
      #   uses: azure/aks-set-context@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     cluster-name: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      # - name: View Kubernetes Namespaces
      #   run: kubectl get ns
