name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_resource_group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ secrets.AZURE_LOCATION }}
            az role assignment create --role owner --assignee-object-id  ${{ secrets.AZURE_AKS_SP_ID }} --assignee-principal-type ServicePrincipal --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}
            echo "Azure resource group created"
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.10.0
    with:
      templateVersion: 0.10.0
      rg: az-k8s-ldplay-rg
      resourceName: az-k8s-ldplay2
      templateParams: resourceName=az-k8s-ldplay agentCount=1 JustUseSystemPool=true osDiskType=Managed osDiskSizeGB=32 enableTelemetry=false automationAccountScheduledStartStop=Weekday
      postScriptParams: "ingress=contour,monitor=oss"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
