name: Install Otomi

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: azure/setup-kubectl@v1
      #   with:
      #     version: "latest"

      # - uses: azure/setup-helm@v1

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.0.24"

      - uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          use-kubelogin: true

      - name: Install Otomi
        run: |
          helm repo add otomi https://otomi.io/otomi-core
          helm repo update
          helm install otomi otomi/otomi --set cluster.k8sVersion="1.25" --set cluster.name=${{ secrets.AZURE_AKS_CLUSTER_NAME }} --set cluster.provider=azure

      - name: Run kubectl
        run: |
          kubectl get job otomi -w
          kubectl logs jobs/otomi -n default -f
